on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Perform `firebase emulators:exec "npm run jest"`
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install function modules
        run: |
          cd functions
          npm install
      - name: Install `firebase-tools` module globally
        run: npm install -g firebase-tools
      - name: Run `firebase emulators:exec "npm run jest"`
        run: firebase emulators:exec "npm run jest" --project dev
